baseURL = "https://rupakganguly.com/"
Title = "Rupak Ganguly"
languageCode = "en-us"
author = "Rupak Ganguly"

theme = "hyde-hyde"

disqusShortname = "rupakganguly"
googleAnalytics = "UA-125025619-1"
#enableRobotsTXT = true
enableEmoji = true

## Site Settings
[params]
  author = "Rupak Ganguly"
  authorurl = "https://rupakganguly.com/about/"
  description = "personal opinions, experiences and writings..."
  themeColor = "theme-base-0d"
  authorimage = "/img/rg10-square.jpg"
  
  dateformat = "Jan 2, 2006"

  highlightjs = true
  highlightjsstyle = "github"
  #pygmentsCodeFences = true

  relatedPosts = true
  showcomments = true
  #postNavigation = false

  mainSections = ["post"]

[params.meta]
  description = "Rupak Ganguly's blog :: personal opinions, experiences and writings..."
  keywords = "blog,serverless,docker,api,microservices,architecture,aws,lambda,azure,gcp,nodejs,node,alexa,python,java,golang,javascript,thoughts,macos,apple"

[params.social]
  twitter = "rupakg"
  github = "rupakg"
  medium = "rupakg"
  linkedin = "rupakg"
  email = "rupakg+blog@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Webinars"
    identifier = "webinar"
    weight = 300
    url = "/webinars/"    
[[menu.main]]
    name = "Talks"
    identifier = "talk"
    weight = 300
    url = "/talks/"    
##[[menu.main]]
##    name = "Portfolio"
##    identifier = "portfolio"
##    weight = 300
##    url = "/portfolio/"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 900
    url = "/about/"

##[permalinks]
##  posts = "/posts/:year/:month/:slug/"

# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank
    # between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related
    # pages.
    includeNewer = false
    # Will lower case keywords in both queries and in the indexes.
    toLower = false
[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"