baseURL = "http://rupakganguly.com/"
Title = "Rupak Ganguly"
languageCode = "en-us"
theme = "hyde-hyde"
disqusShortname = "rupakg"
##googleAnalytics = "Your tracking code"
highlightjs = true
highlightjsstyle = "github"  
relatedPosts = true
showcomments = true

## Site Settings
[params]
  description = "personal opinions, experiences and writings..."
  themeColor = "theme-base-0d"
  author = "Rupak Ganguly"
  authorimage = "/img/rg10-square.jpg"
  dateformat = "Jan 2, 2006"

[params.social]
  twitter = "rupakg"
  github = "rupakg"
  medium = "rupakg"
