baseURL = "http://rupakganguly.com"
Title = "Rupak Ganguly"
languageCode = "en-us"
theme = "hyde-hyde"

## Site Settings
[params]
  description = "personal opinions, experiences and writings..."
  relatedPosts = true
  disqusShortname = "rupakg"
  googleAnalytics = "Your tracking code"
  author = "Rupak Ganguly"
  authorimage = "/img/rg10-square.jpg"
  dateformat = "Jan 2, 2006"
  highlightjs = true
  highlightjsstyle = "github"  

[params.social]
  twitter = "rupakg"
  github = "rupakg"
  medium = "rupakg"
